### ISSUE TITLE
Pre-submission Checklist

### ISSUE THREAD

**Issue by WilliamsCJ** [WilliamsCJ/repograph#186]
- [x] Delete results.csv dataset and evaluation repositories
- [x] Code smells -> Issues
- [x] Update number of tests and code coverage percentage
- [x] Fix bibliograph
- [x] Semantic search -> Semantic code search
- [x] Center captions
- [x] Cardinality for ontology
- [x] Multi-repo neo4j screenshot
- [x] FastAPI docs screenshot
- [x] Redo screenshots
- [x] UI features section
- [x] Declaration
